# Generated by Django 2.2 on 2019-05-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='hero/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=200)),
                ('sub_headings', models.CharField(max_length=100)),
            ],
        ),
    ]
